### ISSUE TITLE
Bug: hide wxWindow interface properties that forms can't use

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#1029] opened 2023-06-02 00:40 UTC
### Description:

Forms like wxFrame that use the `wxWindow` xml interface have `derived_` properties which are ignored. The UI should hide these properties since they have no effect.

**Comment by Randalphwa** [comment] 2024-11-24 22:44
First off, this is a feature request, not a bug. Secondly, there are no more `derived_` properties. There are `subclass` properties, but those are valid.

Closing unless more specific details provided.

**Closed by Randalphwa** 2024-11-24 22:44 UTC
Labels: bug
