### ISSUE TITLE
Bug: Adding tools on wxAuiToolBar the "var_name" member is not created into header file

### ISSUE THREAD

**Issue by rossanoparis** [KeyWorksRW/wxUiEditor#1260] opened 2023-11-02 16:47 UTC
### Description:

in this example the var_name `m_pTool2` is not created into header file.
![image](https://github.com/KeyWorksRW/wxUiEditor/assets/33904565/6e5cef0e-77d9-493c-b307-f310ee287c67)

**Comment by KeyWorksRW** [comment] 2023-11-03 04:13
I have this vague recollection that there was a bug in wxWidgets involving the return value from wxAuiToolbar::AddTool(). I'll check that out and see if it a) was a problem and b) if it has been fixed in 3.2 or later. If the returned pointer doesn't persist, then class access shouldn't be given as an option. If it persists, it will still cause a GPF if wxAuiToolbar::DeleteTool() is called and then the variable is accessed. Nothing I can do about that, though, other than add a warning to the description of the property.

**Comment by rossanoparis** [comment] 2023-11-03 13:38
I understand, but actually the user is obliged to insert a variable.
In my opinion, it would be enough to let the variable empty.
For sure now I0m not able to compile my application, because of missing variable member.

**Comment by KeyWorksRW** [comment] 2023-11-03 15:10
Change class access to `none` and it should compile unless you are actually accessing it in a derived class. In any event, it's next on my fix list.

**Comment by KeyWorksRW** [comment] 2023-11-03 15:15
Issue #23514 in the wxWidgets database is the one I was thinking of. It was a regression, since fixed, so it _should_ be safe to store the variable as a class member.

**Closed** 2023-11-03 19:29 UTC
Labels: bug
