### ISSUE TITLE
Bug: Assigning a font to a window generate a wrong source code.

### ISSUE THREAD

**Issue by rossanoparis** [KeyWorksRW/wxUiEditor#1270] opened 2023-11-05 16:04 UTC
### Description:

wxUiEditor version: latest daily build

Issue noticed during importing from wxFormBuilder

wxDialog font assignment
![image](https://github.com/KeyWorksRW/wxUiEditor/assets/33904565/1335f6b7-3760-470c-95f4-7bb43e2056d8)

Generated code
![image](https://github.com/KeyWorksRW/wxUiEditor/assets/33904565/7f80f31f-a65a-4c0b-b1ba-37df3fe2dea6)
::GetFont() function needs a parameter and its result value is not a pointer.
There is no font size assignment.

I think the code should be like this
`m_pMessage->SetFont( wxFont( 16, wxFONTFAMILY_DEFAULT, wxFONTSTYLE_NORMAL, wxFONTWEIGHT_NORMAL, false, wxEmptyString ) );`

**Comment by KeyWorksRW** [comment] 2023-11-06 18:34
Reproducing this is a bit tricky. There are only two ways to hit the code that generates the empty GetFont(): 1) non-default gui font, fractional point size with wxWidgets 3.1 requested, 2) non-default gui font, negative point size. The first scenario appears to only affect C++ code, the second one also breaks Python and Ruby code.

The puzzling part is how to get the above screen shot of the wxDialog font assignment from a wxFormBuilder project. If I just set the point size to 16, it doesn't generate the empty GetFont(), but does generate an invalid wxFontInfo construction (font size should be a double, or it will be interpreted as a weight not a pt size).

**Comment by rossanoparis** [comment] 2023-11-07 06:37
I understand ... despite all, it happened.
Perhaps you underestimate one of general [Murphy's law ](https://www.cs.cmu.edu/~fgandon/miscellaneous/murphy/)
_"If anything simply cannot go wrong, it will anyway."_ :)

**Comment by Randalphwa** [comment] 2023-11-08 17:37
I'm concerned about the wxFormBuilder resulting in the font property from your screen shot, while clearly having a very different setting that isn't being displayed in the property. Is there any chance you could attach the wxFormBuilder project that caused the problem? I'd like to step through the importing code in the debugger and find out why the conversion isn't working as expected. I've tried creating different fonts in wxFB, but I have not been able to reproduce the importing problem.

As for the rest of the issue, I'm going to overhaul the font generation code to account for a negative point size, and condense the use of wxFontInfo.

As an aside, I prefer using wxFontInfo to SetFont because when reading the code, you know exactly what the functions are doing. In your SetFont example, a reader who isn't thoroughly familiar with that function would have no idea what the `false` parameter does. wxFontInfo works like wxSizerFlags -- the class methods can be chained together, and are descriptive to the reader of what they are doing.

**Comment by rossanoparis** [comment] 2023-11-08 19:55
It is easy to reproduce.
The following picture show how to get the wrong code.
It is necessary to type a size value equal or less than 0 into the property text.
![image](https://github.com/KeyWorksRW/wxUiEditor/assets/33904565/c3147d1b-743a-4cbd-aeab-e32b0d4738a3)

**Closed** 2023-11-10 00:25 UTC
Labels: bug
