### ISSUE TITLE
Bug: Mockup changing to first page when panel added to a page

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#224] opened 2021-05-16 12:16 UTC
### Description:

When you add a panel to a ribbon page, mockup doesn't re-display the page that the panel was added to, instead displaying the first page.

**Comment by Randalphwa** [comment] 2021-11-06 13:55
I can't reproduce this now -- I did a bunch of work on selection handling a few months back, so apparently this got fixed in the process. If it re-occurs, I'll need repro steps.

**Closed by Randalphwa** 2021-11-06 13:55 UTC
Labels: bug, not reproducible
