### ISSUE TITLE
Bug: wxUiEditor crashes on foreground or background colour changing

### ISSUE THREAD

**Issue by rossanoparis** [KeyWorksRW/wxUiEditor#1407] opened 2024-02-09 16:14 UTC
### Description:

wxUiEditor version: 1.2.0.1 (Daily build 9 Feb)

The crash reported by the video below occurs for each widgets, not only for wxTextCtrl, every time you need to change foreground or background colours.

![crash](https://github.com/KeyWorksRW/wxUiEditor/assets/33904565/6dd914b8-a2e5-457f-a5ed-0ea3f740f594)

**Comment by KeyWorksRW** [comment] 2024-02-12 04:22
The crash is in the dtor for AutoSystemDpiAware so this is a regression in the wxWidgets 3.3 code I just picked up in order to work on integration of lunasvg into wxWidgets. I'll track this down and fix it in the wxWidgets code and get a PR there submitted, then copy the fix here to get the daily builds working again.

**Comment by KeyWorksRW** [comment] 2024-02-12 04:31
Heh, turns out it was already discovered and fixed. I picked up the fix, and I think it got picked up before the daily builds start, so it should be in the 2/12 daily build. I'll check it myself in the morning, and close this if it's fixed.

**Comment by rossanoparis** [comment] 2024-02-12 07:29
Thank you @KeyWorksRW it works

**Comment by KeyWorksRW** [comment] 2024-02-12 13:32
Glad you spotted it -- I would have picked up the fix after lunasvg gets merged into wxWidgets, but that's probably not going to happen for a couple of weeks.

**Closed by KeyWorksRW** 2024-02-12 13:32 UTC
Labels: bug, crash, high priority
