### ISSUE TITLE
Bug: C/C++ logical error with embedded images variable name

### ISSUE THREAD

**Issue by amreisa** [KeyWorksRW/wxUiEditor#960] opened 2023-03-20 23:50 UTC
### Description:
I got logical error with embedded images variable name When I try Add use image have numeric numbers file name like 222.xpm for example the bin2c code part generator variable name like this 222_xpm[] this will lead to build time error like **_expected unqualified-id const unsigned char_**, And I think variable name generator must add some letters at start to work with **C/C++ variable name rules**

Thanks.
Amr

**Comment by KeyWorksRW** [comment] 2023-03-21 02:00
Filenames allow a lot more characters then C++ variables do. Besides the problem with initial numbers indicated above, it also won't work if the filename contains unicode, symbols, etc. We're going to need a function to convert the filename string into a usuable C++ variable string, keeping in mind that the image function names will also need this string as a suffix. Depending on the OS, filenames can potentially be 2048 characters long, but C++ only allows 255 character lengths (or at least some compilers are limited to that amount).

The open question is whether these names should only be unique to the project, or unique to the filename. If unique to the project, we can easily prevent overly long variable names by keeping a unique counter to add as a replacement and/or suffix. However, that means two projects cannot share modules that contain embedded images without risk of variable name conflict. The conflict is non-resolvable since the images themselves could be different.

I'm marking this as a Design change as well as a Bug since the way function names and variable names are created needs to be designed to run through a conversion routine first.

**Comment by amreisa** [comment] 2023-03-21 11:09
Hello @KeyWorksRW 

I think quick fix can be done by check file name and if not OK with C/C++ variable name rules it will ask user for variable name or ability to change image variable name in GUI.

Best rereads,
Amr

**Comment by KeyWorksRW** [comment] 2023-03-21 15:17
The conversion function will need to create the initial variable name because it will need to be unique amongst all of the images used in the project. It would be possible to present a suggested name, but the dialog would need to ensure that the user not change the name to something that conflicts with the name created for a different image in the project.

The header file where the `externs` are declared will include a comment with the original filename to make it easier to identify if the variable name is quite different. The same will be for the Python files, though in this case the comment would be where the image is defined.

Once I get the conversion code working, I'll be creating some sample image files with a variety of non-C++-compatible filenames. I'll post the results here so you can see what they'll look like and then consider whether or not you still think an option for the user to change them is valuable.

**Comment by KeyWorksRW** [comment] 2023-03-21 20:15
Here are some examples of what it will look like. The name in comments is the orignal filename:

```c++
    // Ainsi ça se passe.png
    const unsigned char Ainsi_c3_a_se_passe_png[148] {

    // bottom(1).png
    const unsigned char bottom_1__png[148] {

    // 1_bottom.png
    const unsigned char img_1_bottom_png[148] {
```

In Python, this would be:

```python
    # Ainsi ça se passe.png
    Ainsi_c3_a_se_passe_png = PyEmbeddedImage(
```

**Comment by KeyWorksRW** [comment] 2023-06-30 00:11
I'm reopening this because if the entire image name contains UTF8 characters then the entire variable name generation fails to generate a unique name (in fact currently, it throws an exception).

I think @amreisa amreisa is right -- there needs to be a way for the user to override the name. One idea would be to create an additional `embedded_name` property that would be added as a third or fourth field in the entire bitmap property string. This would get automatically filled in when the user specifies the image name using the filename as the starting point. We could make a check to enforce uniquness at the form level (or the project level if the image is being added to the Images List). The user could override that if they want. If the user doesn't override it, and the value is the same as the filename, then it would not be saved to the project file, matching existing behaviour and project files.

**Comment by KeyWorksRW** [comment] 2023-07-11 18:54
I've done some initial work on supporting an alternate variable name, but this is a _major_ change that will affect numerous areas of the code. Given the amount of work and coding and that the 1.1.2 release is already overdue, this unfortunately needs to wait until after this release. The code is in better shape than it was, since it can handle some filenames with non-C++ characters, but full for support needs to wait until after this upcoming release.

**Comment by KeyWorksRW** [comment] 2024-02-12 15:09
I had hoped to add an `Alternate name` or even a `var_name` property to embedded/svg images. While it would work for svg images, it will _not_ work for bundled images. The problem is that the dev only specifies the first filename -- the rest of the filenames are determined based on that initial filename (similar to what wxWidgets does). Each of those additional filenames also need to have a variable name, but the dev has no way to set them. Even if they could set them, it would break the moment an additional file with the DPI naming pattern was added, or if a filename was removed.

The current FileNameToVarName() function prefixes a filename with "img_" if the filename starts with a digit and converts a '.' to a '_'. For any other non-numeric character, it will convert the first non-alphanumeric character to '_', and any additional non-alphanumeric characters immediately following will be converted to a 2-letter hex string. If it looks like the variable name will exceed 256 characters, then the final part of the name will have a "_name_truncated" suffix.

Note that in terms of wxUiEditor code generation, it doesn't really matter what the variable name is as long as it it unique to the form it is used in. In theory, it could be just a hash of the filename converted to a hex string. However, that makes it more difficult to use outside of the generated code (i.e., derived class).

Closing, since I think this is as close as I can get to providing support for UTF-8 and other filenames that need to be modified to work as a variable name in all the computer languages we support.

**Closed by KeyWorksRW** 2024-02-12 15:09 UTC
Labels: bug, design change
